### PR TITLE
Workshop Manager

### PR DESCRIPTION
**Pull request by samisalreadytaken**
Create, edit, publish workshop items in-game. Based on CSGO's Workshop Publish tool.

I didn't want to spend 10 minutes logging into steamcmd, so I spent a day implementing this tool.

This can only display 50 workshop items at the moment.

All edge cases aren't tested, and there are adjustments to be made, but it works very well as is.

Video: https://www.youtube.com/watch?v=Tb_UdBT4U38

In comparison,

CSGO: https://i.imgur.com/kJ7ZW3q.png

HLVR & L4D2: https://i.imgur.com/ZMYIT0q.png

---

Edit: added the delete button for completeness sake. Made the confirmation button red and added a 1 second button activation delay for safety.

---

Edit: Implemented JPEG decompression and preview image display, and fixed the descriptions. Now workshop item preview images and the entirety of descriptions are downloaded, and properly displayed.

However `jpeglib.lib` is missing in the 2013 SDK. Fixing this you would have to either build the [source](https://www.ijg.org/files/) yourself with optionally setting up vpc scripts for it - which is a lot of work, or get Valve's pre-built library from Alien Swarm SDK.

2013 SDK libjpeg headers are version 8 while ASW SDK libjpeg is version 6b. So you would have to get 6b headers from there as well.

If you do decide to include libjpeg library, the header inclusion in workshop_publish.cpp needs to be uncommented. If you include it before merging this PR, I can also enable it.

### CODE REVIEW

**Comment by 1upD** [comment]
This looks incredible! I built this branch locally and tested it out, and I was able to update a hidden addon with a description and image. We will be reviewing this soon and hopefully can include it in our next update.

**Review by 1upD — APPROVED** [review]
This looks great to me! I checked out the branch and tried it out in-game previously. I am approving this PR with the intent of merging it before our next update.

**Comment by 1upD** [comment]
Regarding libjpeg, I think we can merge without it for now (for the creation of an update planned tomorrow) and make a separate PR to add the library as it adds a small amount of overhead. I should create an issue to track that. I really appreciate all the work on this

**Comment by 1upD** [comment]
For due diligence, I checked out the branch and compiled again. I noticed that when I selected "unlisted" in the dropdown and published, my addon went public. I tried setting it to friends only or hidden, and I even tried selecting the addon folder and image and republishing. None of my change notes for that addon (https://steamcommunity.com/sharedfiles/filedetails/?id=2869994513) show up and it always changes it from Hidden to Public.

**Comment by 1upD** [comment]
I also tried uploading a new addon with the same content and image. The upload worked just fine but it did upload as public and note private.

**Review by 1upD — CHANGES_REQUESTED** [review]
Uploads through the workshop manager always upload with visibility "public" regardless of selection

**Comment by samisalreadytaken** [comment]
Fixing KeyValues leaks apparently caused menu item KeyValues values to reset to 0, which is public visibility. I reverted that change now.

Steam keeps checksums of contents, so workshop files won't be updated if content was not changed. Make a change in the content to be able publish change notes.

**Review by 1upD — APPROVED** [review]
That worked! Thank you so much Sam

**Comment by 1upD** [comment]
@samisalreadytaken I am adding you to the in-game credits for creating the workshop manager under a new section called "GitHub Contributors" with the name 'samisalreadytaken'. Is that alright, or would you prefer to be credited differently?

I haven't forgotten about the JPEG decompression library and I will be adding that in the future. I might log that under 'Issues' later today

**Comment by samisalreadytaken** [comment]
That name is fine.

You might also want to mention [libpng](https://github.com/glennrp/libpng) as well. I added PNG reading earlier today. Even though, unlike jpeglib, there is no libpng in the SDKs to simply copy-paste from, the code for it is there and functional if you ever decide to add it.

**Comment by IBRS-4Ever** [comment]
Localization support?

**Pull request merged**
